### ISSUE TITLE
turn off the alarm by clicking on the USB mouse

### ISSUE THREAD

**Issue by jiyangg** [fewieden/MMM-AlarmClock#11]
Platform (Hardware/OS): RaspberryPi 3 Model B+, Raspbian

Node version: 8.10.0

MagicMirror version: 2.2.2

Module version: 1.1.0

Description of the issue: Hope to turn off the alarm by clicking on the USB mouse.

**Comment by jiyangg** [comment]
I found a way. Because MagicMirror default hides the mouse, so need to let the mouse display. 

MagicMirror/css/custom.css
```css
 body {
    cursor: default;
   //or
   //cursor: hide;
 }
```
